name = "myartpage"
version = "0.0.1"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[tailwind]
args = [
  "--config=tailwind.config.js",
  "--input=./src/css/app.css",
  "--output=./priv/static/css/app.css",
]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
wisp = ">= 0.16.0 and < 1.0.0"
lustre = ">= 4.3.2 and < 5.0.0"
lustre_hx = ">= 0.1.13 and < 1.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
gleam_otp = ">= 0.10.0 and < 1.0.0"
mist = ">= 1.2.0 and < 2.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
youid = ">= 1.2.0 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
logging = ">= 1.3.0 and < 2.0.0"
cake = ">= 1.0.1 and < 2.0.0"
decode = ">= 0.2.0 and < 1.0.0"
argus = ">= 1.0.1 and < 2.0.0"
dot_env = ">= 1.1.0 and < 2.0.0"
prng = ">= 3.0.3 and < 4.0.0"
formal = ">= 2.0.0 and < 3.0.0"
birl = ">= 1.7.1 and < 2.0.0"
gleam_pgo = ">= 0.14.0 and < 1.0.0"
simplifile = ">= 2.0.1 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
glailglind = ">= 1.1.3 and < 2.0.0"
